[functions]
directory = "functions"

[[redirects]]
# Do not push this redirect to a versioned branch!
from = "/1.0/*"
to = "https://v1.internal-api-screenshot.netlify.app/:splat"
status = 301
force = true

[[redirects]]
# Do not push this redirect to a versioned branch!
from = "/*"
to = "https://v1.internal-api-screenshot.netlify.app/:splat"
status = 301
force = true
