[functions]
directory = "functions"

[[headers]]
  for = "/static/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
from = "/static/*"
to = "/static/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/.netlify/builders/screenshot"
status = 200
force = true
