[build]
publish = "static"

[functions]
directory = "functions"

[[redirects]]
from = "/static/*"
to = "/static/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/.netlify/builders/screenshot"
status = 200
force = true
